package main

type fileStatus uint8

const (
	fileStatusUnknown fileStatus = iota
	fileStatusNoCopyright
	fileStatusWithCopyright
	fileStatusCopyrightYearNeedsUpdated
	fileStatusCannotFindCopyrightYear
	fileStatusAutoGenerated
	fileStatusOtherCopyright
	fileStatusTooBig
	fileStatusCannotOpen
	fileStatusError // Keep this one last!
)

func (f fileStatus) String() string {
	switch f {
	case fileStatusNoCopyright:
		return "add copyright data"
	case fileStatusWithCopyright:
		return "found copyright data"
	case fileStatusCopyrightYearNeedsUpdated:
		return "copyright year needs updated"
	case fileStatusCannotFindCopyrightYear:
		return "cannot find a year in the copyright header"
	case fileStatusAutoGenerated:
		return "ignore auto-generated file"
	case fileStatusOtherCopyright:
		return "ignore other copyright"
	case fileStatusTooBig:
		return "file is too big"
	case fileStatusCannotOpen:
		return "cannot open file"
	case fileStatusError:
		return "general read/write error"
	}
	return ""
}

func (f fileStatus) Symbol() string {
	switch f {
	case fileStatusNoCopyright:
		return "+"
	case fileStatusWithCopyright:
		return "."
	case fileStatusCopyrightYearNeedsUpdated:
		return "^"
	case fileStatusCannotFindCopyrightYear:
		return "Y"
	case fileStatusAutoGenerated:
		return "-"
	case fileStatusOtherCopyright:
		return "_"
	case fileStatusTooBig:
		return "O"
	case fileStatusError:
		return "!"
	case fileStatusCannotOpen:
		return "X"
	case fileStatusUnknown:
		return "?"
	}
	return " "
}
