package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"
	"strconv"
	"strings"
	"time"

	"github.com/creativeprojects/clog"
	"github.com/vbauerster/mpb/v5"
	"github.com/vbauerster/mpb/v5/decor"
)

func checkForCopyrightNotices(copyrightNotice []byte) {
	start := time.Now()
	progress := mpb.New()
	bar := progress.AddBar(int64(fileQueue.Len()),
		mpb.PrependDecorators(decor.CountersNoUnit("files: %d / %d", decor.WC{})),
		mpb.BarRemoveOnComplete())
	for e := fileQueue.Front(); e != nil; e = e.Next() {
		bar.Increment()
		fileEntry := e.Value.(FileEntry)
		checkForCopyrightNoticeInFile2(fileEntry, copyrightNotice)
	}
	progress.Wait()
	clog.Infof("finished analyzing files in %s", time.Since(start))
}

func checkForCopyrightNoticeInFile(fileEntry FileEntry, copyrightNotice []byte) {
	var err error

	buffer, err := readFile(fileEntry.Name)
	if err != nil {
		return
	}
	ignore := autoGenerated.FindIndex(buffer)
	if ignore != nil {
		progress(fileEntry.Name, fileStatusIgnore, nil)
		return
	}
	// Use the regexp to detect if the copyright header is present
	found := detectOtherHeader.FindIndex(buffer)
	if found != nil {
		// Header was found, now we need to check if the year is right
		yearMatch := detectOwnHeader.FindSubmatch(buffer)
		// yearMatch: The first []byte is the whole match, then each one after are from the capturing parenthesis:
		// so the next one will be the string before the year, then the year, then the rest of the line
		if yearMatch == nil || len(yearMatch) <= 3 {
			// Really, we should have found a year
			progress(fileEntry.Name, fileStatusError, fmt.Errorf("a year was not found in the copyright notice"))
			return
		}
		if len(yearMatch) > 4 {
			// So there's more than one copyright notice in the file?
			// Convert [][]byte to string for the error message
			displayYearRange := make([]string, len(yearMatch))
			for index, element := range yearMatch {
				displayYearRange[index] = "\"" + string(element) + "\""
			}
			progress(fileEntry.Name, fileStatusError, fmt.Errorf("more than one year was found in the copyright notice: [ %v ]", strings.Join(displayYearRange, ", ")))
			return
		}
		year, err := strconv.Atoi(string(yearMatch[2]))
		if err != nil {
			// not and integer?
			progress(fileEntry.Name, fileStatusError, fmt.Errorf("wrong format of year was found in the copyright notice"))
			return
		}
		currentYear := time.Now().Year()
		if year < currentYear {
			// We need to update the existing copyright header
			if !flags.dryRun {
				buffer = detectOwnHeader.ReplaceAll(buffer, []byte("${1}"+strconv.Itoa(currentYear)+"${3}"))
				err = ioutil.WriteFile(fileEntry.Name, buffer, 0666)
				if err != nil {
					progress(fileEntry.Name, fileStatusError, err)
					return
				}
			}
			progress(fileEntry.Name, fileStatusCopyrightYearNeedsUpdated, nil)
			return
		}
		progress(fileEntry.Name, fileStatusWithCopyright, nil)
	} else {
		// We need to add the new copyright header
		if !flags.dryRun {
			err = addCopyrightNotice(fileEntry.Name, copyrightNotice, buffer)
			if err != nil {
				progress(fileEntry.Name, fileStatusError, err)
				return
			}
		}
		progress(fileEntry.Name, fileStatusNoCopyright, nil)
	}
}

func checkForCopyrightNoticeInFile2(fileEntry FileEntry, copyrightNotice []byte) {
	var err error

	reader, err := getFileReaderFromPool(fileEntry.Name)
	if err != nil {
		return
	}
	defer func() {
		reader.Close()
		bufReaderPool.Put(reader)
	}()

	buf := bufferPool.Get().(*bytes.Buffer)
	defer bufferPool.Put(buf)
	buf.Reset()
	if buf.Cap() < int(fileEntry.Size) {
		buf.Grow(int(fileEntry.Size) - buf.Cap() + 1)
	}
	written, err := io.Copy(buf, reader)
	if err != nil {
		progress(fileEntry.Name, fileStatusError, err)
		return
	}
	if written != fileEntry.Size {
		progress(fileEntry.Name, fileStatusError, fmt.Errorf("wrong size: expected reading %d but read %d", fileEntry.Size, written))
	}
	buffer := buf.Bytes()
	ignore := autoGenerated.FindIndex(buffer)
	if ignore != nil {
		progress(fileEntry.Name, fileStatusIgnore, nil)
		return
	}
	// Use the regexp to detect if the copyright header is present
	found := detectOtherHeader.FindIndex(buffer)
	if found != nil {
		// Header was found, now we need to check if the year is right
		yearMatch := detectOwnHeader.FindSubmatch(buffer)
		// yearMatch: The first []byte is the whole match, then each one after are from the capturing parenthesis:
		// so the next one will be the string before the year, then the year, then the rest of the line
		if yearMatch == nil || len(yearMatch) <= 3 {
			// Really, we should have found a year
			progress(fileEntry.Name, fileStatusError, fmt.Errorf("a year was not found in the copyright notice"))
			return
		}
		if len(yearMatch) > 4 {
			// So there's more than one copyright notice in the file?
			// Convert [][]byte to string for the error message
			displayYearRange := make([]string, len(yearMatch))
			for index, element := range yearMatch {
				displayYearRange[index] = "\"" + string(element) + "\""
			}
			progress(fileEntry.Name, fileStatusError, fmt.Errorf("more than one year was found in the copyright notice: [ %v ]", strings.Join(displayYearRange, ", ")))
			return
		}
		year, err := strconv.Atoi(string(yearMatch[2]))
		if err != nil {
			// not and integer?
			progress(fileEntry.Name, fileStatusError, fmt.Errorf("wrong format of year was found in the copyright notice"))
			return
		}
		currentYear := time.Now().Year()
		if year < currentYear {
			// We need to update the existing copyright header
			if !flags.dryRun {
				buffer = detectOwnHeader.ReplaceAll(buffer, []byte("${1}"+strconv.Itoa(currentYear)+"${3}"))
				err = ioutil.WriteFile(fileEntry.Name, buffer, 0666)
				if err != nil {
					progress(fileEntry.Name, fileStatusError, err)
					return
				}
			}
			progress(fileEntry.Name, fileStatusCopyrightYearNeedsUpdated, nil)
			return
		}
		progress(fileEntry.Name, fileStatusWithCopyright, nil)
	} else {
		// We need to add the new copyright header
		if !flags.dryRun {
			err = addCopyrightNotice(fileEntry.Name, copyrightNotice, buffer)
			if err != nil {
				progress(fileEntry.Name, fileStatusError, err)
				return
			}
		}
		progress(fileEntry.Name, fileStatusNoCopyright, nil)
	}
}
